// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvL9-ZaqGrKyHaMFWpZIj_8LzsolXZww',
    appId: '1:616816988843:web:8ecdbf08cbd1d161459dee',
    messagingSenderId: '616816988843',
    projectId: 'flutter-notification1',
    authDomain: 'flutter-notification1.firebaseapp.com',
    storageBucket: 'flutter-notification1.appspot.com',
    measurementId: 'G-W75NX9RSZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jAZTgrb70NOVqoA6eDeQSj8NH49adbE',
    appId: '1:616816988843:android:1504bd4d2ff656a6459dee',
    messagingSenderId: '616816988843',
    projectId: 'flutter-notification1',
    storageBucket: 'flutter-notification1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEesbOLTAkDAZjUHfmqsTdg68tfN5FXhU',
    appId: '1:616816988843:ios:7c46eea0ada06fad459dee',
    messagingSenderId: '616816988843',
    projectId: 'flutter-notification1',
    storageBucket: 'flutter-notification1.appspot.com',
    iosClientId: '616816988843-g4u4ipg2rddaroohquaff0n7v9sd3mge.apps.googleusercontent.com',
    iosBundleId: 'com.example.praksaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEesbOLTAkDAZjUHfmqsTdg68tfN5FXhU',
    appId: '1:616816988843:ios:7c46eea0ada06fad459dee',
    messagingSenderId: '616816988843',
    projectId: 'flutter-notification1',
    storageBucket: 'flutter-notification1.appspot.com',
    iosClientId: '616816988843-g4u4ipg2rddaroohquaff0n7v9sd3mge.apps.googleusercontent.com',
    iosBundleId: 'com.example.praksaFrontend',
  );
}